image:
  - Visual Studio 2022

version: 1.0.{build}

clone_depth: 1

nuget:
  project_feed: true

deploy:
  - provider: NuGet
    api_key: $(NuGetApiKey)
    artifact: bin/nuget/*.nupkg

before_build:
  - ps: dotnet restore

build_script:
  - ps: dotnet build --no-restore
  
test_script:
  - ps: dotnet run --project OpenUI-Test

after_build:
  - ps: ls
