image:
  - Visual Studio 2022

version: 1.0.0.{build}

clone_depth: 1

before_build:
  - ps: dotnet restore

build_script:
  - ps: dotnet build --no-restore
  
test_script:
  - ps: dotnet run --project OpenUI-Test
