image:
  - Visual Studio 2022

version: 1.0.0.{build}

nuget:
  project_feed: true

deploy:
  - provider: NuGet
    symbol_server: https://ci.appveyor.com/nuget/openui-ui74l0bfp806/api/v2/package
    api_key:
      secure: $(NuGetApiKey)
    artifact: bin/nuget/*.nupkg

artifacts:
  - path: bin/nuget/*.nupkg
    name: OpenUI Nuget Packages

configuration: Release

before_build:
  - ps: nuget package OpenUI.nuspec
