image:
  - Visual Studio 2022

version: 1.0.{build}

clone_depth: 1

nuget:
  project_feed: true

init:
  - git config --global core.autocrlf input

configuration: Release

build_script:
  - dotnet restore
  - dotnet build --no-restore

test_script:
  - dotnet run --project OpenUI-Test
