blank_issues_enabled: false
contact_links:
  - name: "💬 General Discussion & Questions"
    url: "https://github.com/YOUR_REPO/discussions"
    about: "For general questions and discussions, please use GitHub Discussions."
